<!-- <?php

// namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
// use Illuminate\Database\Seeder;
// use DB;

// class ProductTableSeeder extends Seeder
// {
//     /**
//      * Run the database seeds.
//      */
//     public function run(): void
//     {
//         DB::table('products')->insert([

//             // fashion
//             [
//                 'product_name' => $product = 't-shirt',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '123456',
//                 'selling_price' => '5000',
//                 'discount_price' => '4000',
//                 'short_descp' => 'this is a t-shirt',
//                 'long_descp' => 'this is a t-shirt',
//                 'product_qty' => '10',
//                 'product_tags' => 'top_product,new_product',
//                 'product_color' => 'white,black,red',
//                 'product_size' => 's,m,l',
//                 'product_thambnail' => 't-shirt.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '0',
//                 'special_offer' => '1',
//                 'special_deals' => '0',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '1',
//                 'subcategory_id' => '1',
//                 'brand_id' => '3',

//             ], [
//                 'product_name' => $product = 'dress',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '123455',
//                 'selling_price' => '15000',
//                 'discount_price' => '14000',
//                 'short_descp' => 'this is a dress',
//                 'long_descp' => 'this is a dress',
//                 'product_qty' => '15',
//                 'product_tags' => 'dress,new_product',
//                 'product_color' => 'white,black,red,green',
//                 'product_size' => 's,m,l',
//                 'product_thambnail' => 'dress.jpg',
//                 'hot_deals' => '0',
//                 'featured' => '1',
//                 'special_offer' => '1',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '1',
//                 'subcategory_id' => '2',
//                 'brand_id' => '3',

//             ], [
//                 'product_name' => $product = 'jeans',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '123555',
//                 'selling_price' => '25000',
//                 'discount_price' => '15000',
//                 'short_descp' => 'this is a jeans',
//                 'long_descp' => 'this is a jeans',
//                 'product_qty' => '12',
//                 'product_tags' => 'buttom_product,new_product',
//                 'product_color' => 'white,black,gray,blue',
//                 'product_size' => 's,m,l,xl',
//                 'product_thambnail' => 'jeans.jpg',
//                 'hot_deals' => '0',
//                 'featured' => '0',
//                 'special_offer' => '1',
//                 'special_deals' => '0',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '1',
//                 'subcategory_id' => '1',
//                 'brand_id' => '4',

//             ], [
//                 'product_name' => $product = 'Sweatshirt And Pants Set',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '125555',
//                 'selling_price' => '25000',
//                 'discount_price' => '20000',
//                 'short_descp' => 'this is a Set',
//                 'long_descp' => 'this is a Set',
//                 'product_qty' => '8',
//                 'product_tags' => 'buttom_product,top_product',
//                 'product_color' => 'white,black,gray,blue',
//                 'product_size' => 's,m,l,xl',
//                 'product_thambnail' => 'kidSet.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '1',
//                 'subcategory_id' => '3',
//                 'brand_id' => '3',

//             ], [
//                 'product_name' => $product = 'Nike Sneakers',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '155555',
//                 'selling_price' => '45000',
//                 'discount_price' => '35000',
//                 'short_descp' => 'this is a Nike(Air Jordan) sneakers',
//                 'long_descp' => 'this is a Nike(Air Jordan 1 low) sneakers',
//                 'product_qty' => '17',
//                 'product_tags' => 'sneakers,new_product',
//                 'product_color' => 'white,black,gray,blue',
//                 'product_size' => '38,39,40,41,42',
//                 'product_thambnail' => 'jordan.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '1',
//                 'special_deals' => '0',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '1',
//                 'subcategory_id' => '4',
//                 'brand_id' => '5',
//             ],
//             /// electronic
//             [

//                 'product_name' => $product = 'Galaxy Buds2 Pro',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '555555',
//                 'selling_price' => '60000',
//                 'discount_price' => '60000',
//                 'short_descp' => 'this is a Galaxy Buds2 Pro',
//                 'long_descp' => 'this is a Galaxy Buds2 Pro',
//                 'product_qty' => '10',
//                 'product_tags' => 'sneakers,new_product',
//                 'product_color' => 'white,black,purple',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'buds.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '0',
//                 'special_offer' => '1',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '2',
//                 'subcategory_id' => '3',
//                 'brand_id' => '2',

//             ], [
//                 'product_name' => $product = 'Apple Watch Ultra',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '555551',
//                 'selling_price' => '700000',
//                 'discount_price' => '650000',
//                 'short_descp' => 'this is a Apple Watch Ultra',
//                 'long_descp' => 'this is a Apple Ultra Smart Watch',
//                 'product_qty' => '5',
//                 'product_tags' => 'smart_watch,new_product',
//                 'product_color' => 'white,black,orange',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'smartwatch.jpg',
//                 'hot_deals' => '0',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '2',
//                 'subcategory_id' => '3',
//                 'brand_id' => '1',

//             ], [
//                 'product_name' => $product = 'PC Gaming Race Model D Gaming Mouse',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '555521',
//                 'selling_price' => '30000',
//                 'discount_price' => '30000',
//                 'short_descp' => 'this is a Glorious PC Gaming Race Model D Gaming Mouse',
//                 'long_descp' => 'this is a Glorious PC Gaming Race Model D Gaming Mouse',
//                 'product_qty' => '6',
//                 'product_tags' => 'smart_watch,new_product',
//                 'product_color' => 'white,black,pink',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'mouse.jpg',
//                 'hot_deals' => '0',
//                 'featured' => '1',
//                 'special_offer' => '1',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '2',
//                 'subcategory_id' => '3',
//                 'brand_id' => '6',

//             ], [
//                 'product_name' => $product = 'Asus ZenBook 14',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '555321',
//                 'selling_price' => '700000',
//                 'discount_price' => '685000',
//                 'short_descp' => 'this is a ASUS ZenBook 14 Ultra-Slim Laptop 14',
//                 'long_descp' => 'this is a ASUS ZenBook 14 Ultra-Slim Laptop 14',
//                 'product_qty' => '10',
//                 'product_tags' => 'laptop,new_product',
//                 'product_color' => 'white,black,gray',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'laptop.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '0',
//                 'special_offer' => '1',
//                 'special_deals' => '0',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '2',
//                 'subcategory_id' => '2',
//                 'brand_id' => '6',

//             ], [
//                 'product_name' => $product = 'iPhone 13 Pro Max',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '554321',
//                 'selling_price' => '700000',
//                 'discount_price' => '685000',
//                 'short_descp' => 'this is a Refurbished iPhone 13 Pro Max 256GB - Gold (SIM-Free)',
//                 'long_descp' => 'this is a Refurbished iPhone 13 Pro Max 256GB - Gold (SIM-Free)',
//                 'product_qty' => '10',
//                 'product_tags' => 'mobile,new_product',
//                 'product_color' => 'white,black,gray,golde,purple',
//                 'product_size' => 'pro_max,pro',
//                 'product_thambnail' => 'iphone.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '1',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '2',
//                 'subcategory_id' => '1',
//                 'brand_id' => '1',

//             ],

//             /// home&kitchen
//             [
//                 'product_name' => $product = 'TORSBY Table',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '654321',
//                 'selling_price' => '40000',
//                 'discount_price' => '30000',
//                 'short_descp' => 'this is a TORSBY Table',
//                 'long_descp' => 'this is a TORSBY Table',
//                 'product_qty' => '7',
//                 'product_tags' => 'table,home_supplies,new_product',
//                 'product_color' => 'white,black,gray,brown',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'table.jpg',
//                 'hot_deals' => '0',
//                 'featured' => '0',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '3',
//                 'subcategory_id' => '1',
//                 'brand_id' => '7',

//             ],
//             [
//                 'product_name' => $product = 'Pans and Pots Set Nonstick',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '111111',
//                 'selling_price' => '46000',
//                 'discount_price' => '46000',
//                 'short_descp' => 'this is a Pans and Pots Set Nonstick',
//                 'long_descp' => 'this is a Pans and Pots Set Nonstick',
//                 'product_qty' => '4',
//                 'product_tags' => 'kitchen_supplies,new_product',
//                 'product_color' => 'white,black,gray,brown',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'pans.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '3',
//                 'subcategory_id' => '2',
//                 'brand_id' => '8',

//             ],
//             [
//                 'product_name' => $product = 'Knife Set',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '111321',
//                 'selling_price' => '12000',
//                 'discount_price' => '12000',
//                 'short_descp' => 'this is a 9-Piece Premium Kitchen High-Carbon Stainless-Steel Blades with Pine Wood Knife Block Set.',
//                 'long_descp' => 'this is a 9-Piece Premium Kitchen High-Carbon Stainless-Steel Blades with Pine Wood Knife Block Set.',
//                 'product_qty' => '25',
//                 'product_tags' => 'kitchen_supplies,new_product',
//                 'product_color' => 'white,black,brown',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'knife.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '0',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '3',
//                 'subcategory_id' => '2',
//                 'brand_id' => '8',

//             ], [
//                 'product_name' => $product = 'Sofa Chair ',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '114321',
//                 'selling_price' => '60000',
//                 'discount_price' => '50000',
//                 'short_descp' => 'this is a Sofa Chair with Gold Metal Legs',
//                 'long_descp' => 'this is a Sofa Chair with Gold Metal Legs',
//                 'product_qty' => '7',
//                 'product_tags' => 'sofa,home_supplies,new_product',
//                 'product_color' => 'white,black,gray,brown,oragne',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'sofa.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '0',
//                 'special_offer' => '1',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '3',
//                 'subcategory_id' => '1',
//                 'brand_id' => '7',

//             ],
//             [
//                 'product_name' => $product = 'JAWS Cleaner',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '111121',
//                 'selling_price' => '6000',
//                 'discount_price' => '6000',
//                 'short_descp' => 'this is a JAWS Cleaner Multi-Surface Kitchen Cleaner Bottle and 2 Refill Pods.',
//                 'long_descp' => 'this is a JAWS Cleaner Multi-Surface Kitchen Cleaner Bottle and 2 Refill Pods.',
//                 'product_qty' => '15',
//                 'product_tags' => 'kitchen_supplies,new_product',
//                 'product_color' => 'white,black,purple,yellow',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'cleaner.jpg',
//                 'hot_deals' => '0',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '0',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '3',
//                 'subcategory_id' => '3',
//                 'brand_id' => '9',

//             ],[
//                 'product_name' => $product = 'Table Desk Lamp',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '444441',
//                 'selling_price' => '20000',
//                 'discount_price' => '20000',
//                 'short_descp' => 'this is a Table Desk Lamp',
//                 'long_descp' => 'this is a Rivet Mid-Century Modern Needle Sloped Table Desk Lamp with Light Bulb and White Drum Shade, 21"H, Brass',
//                 'product_qty' => '10',
//                 'product_tags' => 'lights,home_supplies,new_product',
//                 'product_color' => 'white,gray',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'lamp.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '3',
//                 'subcategory_id' => '1',
//                 'brand_id' => '7',

//             ],
//             /// beauty products
//             [
//                 'product_name' => $product = 'Lip Kit',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '111321',
//                 'selling_price' => '29000',
//                 'discount_price' => '29000',
//                 'short_descp' => 'this is a Kylie Koko K Lip Kit.',
//                 'long_descp' => 'this is a Kylie Koko K Lip Kit.',
//                 'product_qty' => '10',
//                 'product_tags' => 'makeup,lip_product',
//                 'product_color' => 'pink,rose,cherry red,honey brown',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'lipstick.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '4',
//                 'subcategory_id' => '1',
//                 'brand_id' => '10',

//             ], [
//                 'product_name' => $product = 'Fauxfilter Foundation',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '114321',
//                 'selling_price' => '30000',
//                 'discount_price' => '25000',
//                 'short_descp' => 'this is a Huda Beauty Fauxfilter Foundation, Creme Brule, 35 ml.',
//                 'long_descp' => 'this is a Huda Beauty Fauxfilter Foundation, Creme Brule, 35 ml.',
//                 'product_qty' => '15',
//                 'product_tags' => 'makeup,skin_product',
//                 'product_color' => 'Beige, Peach,Rose',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'foundation.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '1',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '4',
//                 'subcategory_id' => '1',
//                 'brand_id' => '11',

//             ], [
//                 'product_name' => $product = ' Facial Treatment Set',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '154321',
//                 'selling_price' => '30000',
//                 'discount_price' => '30000',
//                 'short_descp' => 'this is a The Ordinary Facial Treatment Set! Includes Vitamin C Cream, Hyaluronic Acid Serum and Niacinamide Serum!.',
//                 'long_descp' => 'this is a The Ordinary Facial Treatment Set! Includes Vitamin C Cream, Hyaluronic Acid Serum and Niacinamide Serum! Brightens, Hydrates And Reduces Skin Blemishes! Vegan, Paraben Free & Cruelty Free!.',
//                 'product_qty' => '15',
//                 'product_tags' => 'skincare_product,skin_product',
//                 'product_color' => 'no color',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'ordinaryset.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '0',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '4',
//                 'subcategory_id' => '2',
//                 'brand_id' => '12',

//             ], [
//                 'product_name' => $product = 'Brushes Set',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '654321',
//                 'selling_price' => '16000',
//                 'discount_price' => '16000',
//                 'short_descp' => 'this is a huda Beauty Professional Brushes Set (Pack of 6) .',
//                 'long_descp' => 'this is a huda Beauty Professional Brushes Set (Pack of 6) .',
//                 'product_qty' => '24',
//                 'product_tags' => 'makeup,brushes,skin_product',
//                 'product_color' => 'no color',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'brush.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '4',
//                 'subcategory_id' => '1',
//                 'brand_id' => '10',

//             ], [
//                 'product_name' => $product = 'Hyaluronic Acid Serum',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '222222',
//                 'selling_price' => '40000',
//                 'discount_price' => '40000',
//                 'short_descp' => 'this is a La Roche-Posay Hyalu B5 Pure Hyaluronic Acid Serum for Face, with Vitamin B5, Anti-Aging Serum for Fine Lines and Wrinkles,.',
//                 'long_descp' => 'this is a La Roche-Posay Hyalu B5 Pure Hyaluronic Acid Serum for Face, with Vitamin B5, Anti-Aging Serum for Fine Lines and Wrinkles, Hydrating Serum to Plump and Repair Dry Skin, Safe on Sensitive Skin.',
//                 'product_qty' => '7',
//                 'product_tags' => 'skincare_product,skin_product',
//                 'product_color' => 'no color',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'serum.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '0',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '4',
//                 'subcategory_id' => '2',
//                 'brand_id' => '13',

//             ] ,

//             /// Accessories & Bags
//             [
//                 'product_name' => $product = 'DG Girls bag',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '222221',
//                 'selling_price' => '100000',
//                 'discount_price' => '100000',
//                 'short_descp' => 'this is a DG Girls bag in patchwork denim and plain calfskin in Denim for Women.',
//                 'long_descp' => 'this is a DG Girls bag in patchwork denim and plain calfskin in Denim for Women.',
//                 'product_qty' => '3',
//                 'product_tags' => 'bag,',
//                 'product_color' => 'black,gold,brown',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'bag.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '0',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '5',
//                 'subcategory_id' => '1',
//                 'brand_id' => '14',

//             ],[
//                 'product_name' => $product = 'Womens Square Sunglasses',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '222321',
//                 'selling_price' => '14000',
//                 'discount_price' => '14000',
//                 'short_descp' => 'this is a Dolce & Gabbana DG4384 Womens Square Sunglasses.',
//                 'long_descp' => 'this is a Dolce & Gabbana DG4384 Womens Square Sunglasses.',
//                 'product_qty' => '5',
//                 'product_tags' => 'sunglasses,Accessories',
//                 'product_color' => 'black,gold,grey',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'sunglass.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '5',
//                 'subcategory_id' => '3',
//                 'brand_id' => '14',

//             ],[
//                 'product_name' => $product = 'Casio Bluetooth Watch',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '224321',
//                 'selling_price' => '25000',
//                 'discount_price' => '20000',
//                 'short_descp' => 'this is a Casio Edifice Bluetooth ECB-2000DC-1AEF Sospensione Watch.',
//                 'long_descp' => 'this is a Casio Edifice Bluetooth ECB-2000DC-1AEF Sospensione Watch.',
//                 'product_qty' => '5',
//                 'product_tags' => 'watch,Accessories',
//                 'product_color' => 'black,gold,grey,red',
//                 'product_size' => '5 inches, 5 1/4 inches, 5 1/2 inches , 5 3/4 inches',
//                 'product_thambnail' => 'watch.jpg',
//                 'hot_deals' => '0',
//                 'featured' => '0',
//                 'special_offer' => '1',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '5',
//                 'subcategory_id' => '2',
//                 'brand_id' => '15',

//             ],[
//                 'product_name' => $product = ' Diamond Set',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '254321',
//                 'selling_price' => '100000',
//                 'discount_price' => '90000',
//                 'short_descp' => 'this is a Necklace Bracelet Earrings Diamond Set in 18k White Gold Vermeil.',
//                 'long_descp' => 'this is a Necklace Bracelet Earrings Diamond Set in 18k White Gold Vermeil.',
//                 'product_qty' => '3',
//                 'product_tags' => 'Necklace,Bracelet,Earrings,Set,Accessories',
//                 'product_color' => 'diamond',
//                 'product_size' => '5 inches, 5 1/4 inches, 5 1/2 inches , 5 3/4 inches',
//                 'product_thambnail' => 'nicklace&bracelet.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '0',
//                 'special_offer' => '1',
//                 'special_deals' => '0',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '5',
//                 'subcategory_id' => '2',
//                 'brand_id' => '4',

//             ],[
//                 'product_name' => $product = ' Nike Body Bag',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '654321',
//                 'selling_price' => '25000',
//                 'discount_price' => '25000',
//                 'short_descp' => 'this is a Nike Sportswear Womens Futura 365 Cross-body Bag .',
//                 'long_descp' => 'this is a Nike Sportswear Womens Futura 365 Cross-body Bag .',
//                 'product_qty' => '6',
//                 'product_tags' => 'bag,new_product,Accessories',
//                 'product_color' => 'black,white,green',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'bag2.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '0',
//                 'special_offer' => '0',
//                 'special_deals' => '0',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '5',
//                 'subcategory_id' => '1',
//                 'brand_id' => '3',

//             ]
//             /// toys&games
//             ,[
//                 'product_name' => $product = ' Wooden Jigsaw Puzzles',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '333333',
//                 'selling_price' => '15000',
//                 'discount_price' => '15000',
//                 'short_descp' => 'this is a Puzzles for Kids Ages 3-5, 9 Pack Wooden Jigsaw Puzzles for Toddlers  .',
//                 'long_descp' => 'this is a Puzzles for Kids Ages 3-5, 9 Pack Wooden Jigsaw Puzzles for Toddlers Ages 3-5 16 Pieces Preschool Educational Learning Toys Set Animals Puzzles for 3 4 5 Years Old Boys and Girls Gift .',
//                 'product_qty' => '12',
//                 'product_tags' => 'toys,new_product,puzzle',
//                 'product_color' => 'no_color',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'puzzle.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '4',
//                 'category_id' => '6',
//                 'subcategory_id' => '1',
//                 'brand_id' => '16',

//             ] ,[
//                 'product_name' => $product = ' The Game Plan Game',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '333331',
//                 'selling_price' => '15000',
//                 'discount_price' => '15000',
//                 'short_descp' => 'this is a The Game Plan Game: Life Skills for Kids, Board Game, Kids Card Games Ages 4-10, Family Board Games.',
//                 'long_descp' => 'this is a The Game Plan Game: Life Skills for Kids, Board Game, Kids Card Games Ages 4-10, Family Board Games, Problem-Solving, Feelings Management, Social Skills 2-8 Players .',
//                 'product_qty' => '6',
//                 'product_tags' => 'toys,new_product,board game',
//                 'product_color' => 'no_color',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'game1.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '0',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '6',
//                 'subcategory_id' => '2',
//                 'brand_id' => '16',

//             ],[
//                 'product_name' => $product = ' Barbie Doll ',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '333321',
//                 'selling_price' => '12000',
//                 'discount_price' => '6000',
//                 'short_descp' => 'this is a Barbie Doll with Hair Accessories Pack',
//                 'long_descp' => 'this is a Barbie Doll with Hair Accessories Pack.',
//                 'product_qty' => '10',
//                 'product_tags' => 'toys,new_product,doll',
//                 'product_color' => 'no_color',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'barbietoy.jpg',
//                 'hot_deals' => '0',
//                 'featured' => '0',
//                 'special_offer' => '1',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '6',
//                 'subcategory_id' => '3',
//                 'brand_id' => '17',

//             ]



// ,[
//                 'product_name' => $product = ' UNO ',
//                 'product_slug' => strtolower(str_replace(' ', '-', $product)),
//                 'product_code' => '334321',
//                 'selling_price' => '2000',
//                 'discount_price' => '2000',
//                 'short_descp' => 'this is a UNO - Classic Colour & Number Matching Card Game',
//                 'long_descp' => 'this is a UNO - Classic Colour & Number Matching Card Game - 112 Cards - Customizable & Erasable Wild - Special Action Cards Included - Gift for Kids 7+.',
//                 'product_qty' => '25',
//                 'product_tags' => 'toys,new_product,card_game',
//                 'product_color' => 'no_color',
//                 'product_size' => 'no_size',
//                 'product_thambnail' => 'uno.jpg',
//                 'hot_deals' => '1',
//                 'featured' => '1',
//                 'special_offer' => '0',
//                 'special_deals' => '1',
//                 'status' => '1',
//                 'vendor_id' => '5',
//                 'category_id' => '6',
//                 'subcategory_id' => '3',
//                 'brand_id' => '16',

// ],[
//     'product_name' => $product = ' LEGO Marvel Super Heroes',
//     'product_slug' => strtolower(str_replace(' ', '-', $product)),
//     'product_code' => '354321',
//     'selling_price' => '10000',
//     'discount_price' => '10000',
//     'short_descp' => 'this is a LEGO Marvel Super Heroes - Nintendo Switch',
//     'long_descp' => 'this is a LEGO Marvel Super Heroes - Nintendo Switch , Smash and fly through the Marvel Universe with more than 100 of your favorite Super Heroes and Super Villains',
//     'product_qty' => '9',
//     'product_tags' => 'toys,new_product,lego,super_heros',
//     'product_color' => 'no_color',
//     'product_size' => 'no_size',
//     'product_thambnail' => 'legomarvel.jpg',
//     'hot_deals' => '1',
//     'featured' => '0',
//     'special_offer' => '0',
//     'special_deals' => '1',
//     'status' => '1',
//     'vendor_id' => '4',
//     'category_id' => '6',
//     'subcategory_id' => '3',
//     'brand_id' => '16',

// ],[
//     'product_name' => $product = ' Cube Set',
//     'product_slug' => strtolower(str_replace(' ', '-', $product)),
//     'product_code' => '444444',
//     'selling_price' => '9000',
//     'discount_price' => '9000',
//     'short_descp' => 'this is a Rechargeable Game Activity Cube - 9 Fun Brain & Memory Games',
//     'long_descp' => 'this is a Rechargeable Game Activity Cube - 9 Fun Brain & Memory Games - Cool Toys for Boys and Girls - Christmas/Birthday Gifts for Ages 6-12+ Year Old Kids Tweens & Teens - Best Boy & Girl Toy Gift Ideas',
//     'product_qty' => '6',
//     'product_tags' => 'toys,puzzle,cube_game',
//     'product_color' => 'no_color',
//     'product_size' => 'no_size',
//     'product_thambnail' => 'cubegame.jpg',
//     'hot_deals' => '1',
//     'featured' => '1',
//     'special_offer' => '0',
//     'special_deals' => '0',
//     'status' => '1',
//     'vendor_id' => '4',
//     'category_id' => '6',
//     'subcategory_id' => '3',
//     'brand_id' => '16',

// ]

















//         ]);
    // }
// <!-- } -->
